[project]
name = 'Decentralized-Manufacturing-Autonomous-Production'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.factory-verification]
path = 'contracts/factory-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.human-oversight]
path = 'contracts/human-oversight.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
